version: '3'
services:
  scratch_web:
    container_name: scratch_web
    image: wordpress:5.4.1
    links:
      - scratch_db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: scratch_db
      WORDPRESS_DB_USER: scratch_01
      WORDPRESS_DB_PASSWORD: devpw
      WORDPRESS_DB_NAME: scratch-wpdb
    volumes:
      - ./scratch_site:/var/www/html

  scratch_db:
    container_name: scratch_db
    image: mariadb:10.2
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: scratch-wpdb
      MYSQL_USER: scratch_01
      MYSQL_PASSWORD: devpw
    volumes:
      - scratch_database:/var/lib/mysql
    
  scratch_phpmyadmin:
    container_name: scratch_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - scratch_db
    ports:
      - 8080:80
    environment:
      PMA_USER: scratch_01
      PMA_PASSWORD: devpw
      PMA_HOST: scratch_db
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: scratch-wpdb
      MYSQL_USER: scratch_01
      MYSQL_PASSWORD: devpw

volumes:
    scratch_database: